name: Build mmaction2

on:
  workflow_dispatch:
    inputs:
      torch-version:
        description: "Torch versions, separated with a comma"
        type: string
        default: "2.5.0"
      limit-compute-platform:
        description: "PyTorch compute platforms, separated with a comma"
        type: string
      include-hash:
        description: "Include commit hash in version"
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/_core_build.yml
    with:
      repo: "mmaction2"
      checkout-repo: ${{ github.repository }}
      repo-subdir: "mmaction2"
      torch-version: ${{ inputs.torch-version }}
      limit-python: "3.10"
      limit-compute-platform: ${{ inputs.limit-compute-platform }}
      include-hash: ${{ inputs.include-hash }}
      linux-wheels: true
      windows-wheels: false
      macos-wheels: false
