name: Build opencv-python

on:
  workflow_dispatch:
    inputs:
      repo-tag:
        description: "Repository tag, as in actions/checkout"
        type: string
      limit-python:
        description: "Python versions, separated with a comma"
        type: string
      include-hash:
        description: "Include commit hash in version"
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/_core_build.yml
    with:
      repo: "opencv-python"
      checkout-repo: "opencv/opencv-python"
      repo-tag: ${{ inputs.repo-tag }}
      repo-subdir: ""
      limit-python: ${{ inputs.limit-python }}
      include-hash: ${{ inputs.include-hash }}
      linux-wheels: true
      windows-wheels: false
      macos-wheels: false
